"""group member add default id

Revision ID: 9439a12daf16
Revises: ad5ead2aa5f4
Create Date: 2023-03-10 09:32:40.754524

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9439a12daf16'
down_revision = 'ad5ead2aa5f4'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
